<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Data\Entities\" />
    <Folder Include="Data\Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\C#Library\SysWorkData\SysWorkData\SysWorkData\SysWork.Data.csproj" />
  </ItemGroup>

</Project>
